# Generated by Django 4.0.3 on 2022-04-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='post/default.png', upload_to='post/%Y/%m/%d/'),
        ),
    ]
