# Generated by Django 4.0.3 on 2022-04-05 23:51

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='post/default.png', upload_to=post.models.path_and_rename),
        ),
    ]
