# Generated by Django 4.0.3 on 2022-04-03 03:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profil',
            new_name='Profile',
        ),
        migrations.RenameField(
            model_name='profildurum',
            old_name='user_profil',
            new_name='user_profile',
        ),
    ]
